name: CI-CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compilar y ejecutar tests
        run: mvn clean test

      - name: Construir imagen Docker
        run: |
          docker build -t myapp:${{ github.run_number }} .

      - name: Login a DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push de la imagen
        run: |
          docker tag myapp:${{ github.run_number }} mydockeruser/myapp:${{ github.run_number }}
          docker push mydockeruser/myapp:${{ github.run_number }}

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout infra
        uses: actions/checkout@v3

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Aplicar infraestructura (IaC)
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Desplegar a Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
